version: '3'
services:
  docker-frontend:
    build: ./client
    container_name: 'docker-frontend'
  docker-backend:
    build: ./node-backend
    container_name: 'docker-backend'
  docker-database:
    image: 'mysql:latest'
    container_name: 'docker-database'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  nginx:
    build: ./nginx
    ports:
        - 80:80
volumes:
  my-db: