version: '3'
services:
  docker-frontend:
    build: ./client
    container_name: 'docker-frontend'
    networks:
      - app-network
  nginx:  
    build: ./nginx
    ports:
        - "80:80"
        - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge