version: '3'
services:
  docker-frontend:
    build: ./client
    container_name: 'docker-frontend'
    networks:
      - app-network
  docker-backend:
    build: ./node-backend
    container_name: 'docker-backend'
    networks:
      - app-network
  docker-database:
    image: 'mysql:latest'
    container_name: 'docker-database'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
  nginx:  
    build: ./nginx
    ports:
        - "80:80"
        - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge